version: '3.8'

services:
  backend:
    build: ./backend
    container_name: reflexai-backend
    ports:
      - "8000:8000"
    environment:
      - DELETE_AFTER_ANALYSIS=true
      - OLLAMA_MODEL=llama3.2:1b
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: reflexai-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev
    depends_on:
      - backend
    networks:
      - app-network

  ollama:
    image: ollama/ollama
    container_name: reflexai-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  ollama_data: